### ISSUE TITLE
Tool Issue

### ISSUE THREAD

**Issue by LievreAI** [EZFNDEV/UEAESKeyFinder#21]
i have error uisng the the on game using ue4.17
unhandled exception. System.IndexOfRangeException: Index was outside the bounds of the array.
at Searcher.FindAllPattern(Int64& t)
at UEAesKeyFinder.Program.Main(String[] args)
![3](https://user-images.githubusercontent.com/84988313/145052359-c38b392f-78af-4195-8f63-0e59539964df.png)
"

**Comment by EZFNDEV** [comment]
I will fix that soon, just use a dump for now
